name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # cambia se usi "main"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Deploy to GitHub Pages
        env:
          GIT_USER: github-actions[bot]
          GIT_EMAIL: github-actions[bot]@users.noreply.github.com
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "$GIT_USER"
          git config --global user.email "$GIT_EMAIL"
          npx gh-pages -d build -b gh-pages
